### ISSUE TITLE
Lighthouse, what is it and how to score the 💯

### ISSUE THREAD

**Issue by zouhir** [SydPWA/talks#2]
## Talk Title
Lighthouse, what is it and how to score the 💯

## Length
30min

## Target Audience
Frontend Developers, UX & UI Experts, Anyone in the web industry.

## Detailed Overview
My personal Blog and Website score us 100/100 and would like to see more websites in the community achieving a very high score.
![screenshot 2017-05-11 22 39 29](https://cloud.githubusercontent.com/assets/5052316/25949678/ad6180ce-369b-11e7-9556-6199b4273332.png)

I am really keen to share my experience with everyone on how did I achieve that score and what steps did I follow while debugging and enhancing both the score and experience.

I'll be speaking briefly about Lighthouse:
- Explain JS performance and choosing the right framework.
- Static files Caching, and SW.
- Manifest.
- CSS and web fonts.
- Images optimization best practices.

Cheers 🍻

**Comment by elisechant** [comment]
@zouhir Wow! nice work getting Lighthouse to give you a 100 score!

The part about "steps did I follow while debugging and enhancing both the score and experience" sounds like would be some really good insights to share. 👍
