### ISSUE TITLE
My vision of the future PWA JavaScript tooling

### ISSUE THREAD

**Issue by koresar** [SydPWA/talks#4]
## Talk Title
My vision of the future PWA JavaScript tooling

## Length
10 min

## Target Audience
Technical. All levels.

## Detailed Overview
The Service Worker API is complex and hard. We need a Service Worker jQuery. And I want to discuss with the tech audience what kind of features and API that JavaScript module should have.

**Comment by zouhir** [comment]
Will that include discussion with the audience about your thoughts? I kinda feel we should allow longer if that's the case.

**Comment by koresar** [comment]
Yeah. Discussion is needed. Please, bump the length the way you see it.
Thanks
