### ISSUE TITLE
IT Game in Sydney

### ISSUE THREAD

**Issue by cedric25** [SydPWA/talks#6]
## Talk Title
IT Game in Sydney

## Length
10 min

## Target Audience
Anyone working in the IT industry

## Detailed Overview
I've been working on a small game with some of my colleagues at OCTO Technology and we'd be very happy to take 10min to present it.
The game itself is a very fun game between geo-catching and IT quiz. Each week, players will have to walk around Sydney to discover new challenge locations and answer IT related questions, covering all kind of subjects.
More info here: http://hidden-challenges.octo.com.au/

My first thoughts about the talk:
- A few slides, present the game, gameplay, start date...
- Tech stack (Vue.js webapp, AWS lambdas, DynamoDB...)
- Solve one challenge together

**Comment by koresar** [comment]
Sounds awesome! I presume it utilises some modern browser stuff like GPS tracking, offline caching, etc?

**Comment by cedric25** [comment]
Thanks! GPS tracking for sure! Offline caching, not yet unfortunately, that'd be a great step if we move forward.

**Comment by koresar** [comment]
Great. :)
We don't know our next meetup date yet. Should be in next 2 months or so. But you're surely in! 👍
